name: Fetch Data From Google SpreadSheets


on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3

 
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r scripts/requirements.txt

    
    - name: Fetch Data
      run: |
        python scripts/fetch_data.py
