name: Fetch Data From Google SpreadSheets

on:
  schedule:
    # every 1 hours from 19 to 0h the job will run
    - cron: "0 19/1 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    python -m pip install -r script/requirements.txt

      - name: Run the main batch file
        run: |
          bash ./main.sh
          echo "Fetch Job Completed"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
    #- name: Add new files to github repo
    #  run: |
    #    git add -A dataset/
    #- name: Commit all changes
    #  uses: stefanzweifel/git-auto-commit-action@v4.1.1
    #  with:
    #    commit_message: Update data for today
    #    branch: master
    #  if: always()
