name: Fetch Data From Google SpreadSheets


on:
  schedule:
    # every 10 minutes the job will run
    - cron: "*/5 * * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3

 
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r script/requirements.txt

    
    - name: Fetch Data
      run: |
        python script/fetch_data.py
